-- Apps
hl.bind("SUPER + ESCAPE",         hl.dsp.exec_cmd("nyhud.sh rofi session"))
hl.bind("SUPER + SHIFT + ESCAPE", hl.dsp.exec_cmd("nylaunch.sh btop"))
hl.bind("SUPER + SPACE",          hl.dsp.exec_cmd("nyhud.sh rofi launcher"))
hl.bind("SUPER + V",              hl.dsp.exec_cmd("nyhud.sh rofi clipboard"))
hl.bind("SUPER + PERIOD",         hl.dsp.exec_cmd("nyhud.sh rofi emoji"))
hl.bind("SUPER + B",              hl.dsp.exec_cmd("zen-browser"))
hl.bind("SUPER + Y",              hl.dsp.exec_cmd("kitty -e yazi ~/Downloads/"))
hl.bind("SUPER + Return",          hl.dsp.exec_cmd("kitty"))

-- Windows
hl.bind("SUPER + F", hl.dsp.window.fullscreen_state({internal = 2, client = 0, action = "toggle"}))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), {mouse = true})
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), {mouse = true})
hl.bind("SUPER + Q", hl.dsp.window.kill())
hl.bind("SUPER + J", hl.dsp.group.toggle())
hl.bind("SUPER + SHIFT + UP", hl.dsp.window.move({direction = "u"}))
hl.bind("SUPER + SHIFT + DOWN", hl.dsp.window.move({direction = "d"}))
hl.bind("SUPER + SHIFT + LEFT", hl.dsp.window.move({direction = "l"}))
hl.bind("SUPER + SHIFT + RIGHT", hl.dsp.window.move({direction = "r"}))
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({workspace = "-1", follow = true}))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({workspace = "+1", follow = true}))

-- Navigation
hl.bind("SUPER + UP", hl.dsp.focus({direction = "u"}))
hl.bind("SUPER + DOWN", hl.dsp.focus({direction = "d"}))
hl.bind("SUPER + LEFT", hl.dsp.focus({direction = "l"}))
hl.bind("SUPER + RIGHT", hl.dsp.focus({direction = "r"}))
hl.bind("SUPER + TAB", hl.dsp.focus({workspace = "+1", on_current_monitor = true}))
hl.bind("SUPER + SHIFT + TAB", hl.dsp.focus({workspace = "-1", on_current_monitor = true}))
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("special"))
