## HYPRLAND DEFAULTS
windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

## CUSTOM RULES
layerrule{
    name = rofi_blur
    match:namespace = rofi
    blur =  true
    dim_around = true
}
 
windowrule {
    name = nyapps
    match:class = ^(nya-.*)$
    center = true
    float = true
    dim_around = true
}


# Float steam sub-apps
windowrule {
    name = steam-popups
    match:class = steam
    match:title = .+
    float = true
    center = true
    max_size = 50% 50%
}
windowrule {
    name = steam-main
    match:class = steam
    match:title = ^(Steam)$
    float = false
}

# Float browser steam sub-apps
windowrule {
    name = zen-popups
    match:initial_class = zen
    match:initial_title = .+
    float = true
    center = true
    max_size = 50% 50%
}

windowrule {
    name = zen-main
    match:initial_class = zen
    match:initial_title = ^(Zen Browser)$
    float = false
}
