[mgr]
prepend_keymap = [
    # =======================================================================
    # Core Essentials
    # =======================================================================
    { on = [ "?" ], run = "help", desc = "Core: Open help menu" },
    { on = [ "q" ], run = "quit", desc = "Core: Quit without picking" },
    { on = [ "w" ], run = "show", desc = "Core: See active tasks/proceses" },


    # =======================================================================
    # Plugins (Prefix: \ )
    # Pressing '\' will pop up a menu showing these options:
    # =======================================================================
    { on = [ "\\", "m" ], run = "plugin mount",   desc = "Plugin: Open drive mounting manager" },
    { on = [ "\\", "v" ], run = "plugin gvfs",    desc = "Plugin: Open GVFS manager (Network/Trash)" },
    { on = [ "\\", "c" ], run = "plugin ouch",    desc = "Plugin: Compress or Decompress (ouch)" },
    { on = [ "\\", "p" ], run = "plugin chmod",   desc = "Plugin: Change permissions (chmod)" },
    { on = [ "\\", "g" ], run = "plugin lazygit", desc = "Plugin: Open LazyGit UI" },
    { on = [ "\\", "f" ], run = "plugin yafg",    desc = "Plugin: Fuzzy find/grep (yafg)" },
    { 
        on   = [ "\\", "y" ], 
        run  = "shell 'file=\"$1\"; mime=$(file --mime-type -b \"$file\"); wl-copy --type \"$mime\" < \"$file\" && notify-send \"Yazi\" \"Copied $(basename \"$file\") to clipboard\"'", 
        desc = "Plugin: Yank file content to Wayland clipboard" 
    },
]

[pick]
prepend_keymap = [
    { on = [ "g", "s" ], run = "close --submit", desc = "Confirm" }
]
