[mgr]
show_hidden = true
sort_by = "natural"
sort_translit = true
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_symlink = true
mouse_events =  ["scroll","click"]


[opener]
edit = [
    { run = '${EDITOR} "$@"', block = true, desc = "Edit File" }
]
run = [
    {run = 'exec "$@"', block = true, desc = "Run bash..."}
]
extract = [
    { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" }
]

edit_word = [
    { run = 'micro "$@"', block = true, desc = "Open with Micro"}
]
view_image = [
    { run = 'photoflare "$@"', desc = "Open with Photoflare" }
]
view_video = [
    { run = 'vlc "$@"', desc = "Open with VLC" }
]
[open]
rules = [
    { url  = "*.sh", use = ["edit", "run"] },
    { mime = "text/shellscript", use = ["edit", "run"] },
    { mime = "text/*", use = ["edit", "edit_word"] },
    { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", use = "extract" },
    { mime = "image/*", use = "view_image" },
    { mime = "video/*", use = "view_video" },
    { mime = "*", use = "edit" }
]

[plugin]
prepend_fetchers = [
    { group = "git", url = "*", run = "git" },
    { group = "git", url = "*/", run = "git" }
]
prepend_previewers = [
    { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run  = "ouch" },
    { mime = "image/svg+xml", run = "magick" }
]
